version: "3"

services:
  web:
    container_name: "my_sql_dump"
    build: .
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - .:/var/www/html:delegated
    tty: true
    stdin_open: true